# Generated by Django 2.1.3 on 2018-11-18 12:41

import PathBreakers.Models.PathBreaker
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathBreaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('profilePic', models.ImageField(default='static/PathBreakers/Default.png', upload_to='static/PathBreakers')),
                ('yog', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_yog', message='invalid year of graduation', regex='^[1-9][0-9]{3}-[1-9][0-9]{3}$'), PathBreakers.Models.PathBreaker.YOGValidator])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pathbreaker',
            name='Profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PathBreakers.Profession'),
        ),
    ]
